version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"  # Use port from .env
    depends_on:
      - mongodb
    env_file:
      - .env  # Load environment variables from .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
