export const FETCH_SESSIONS_REQUEST = 'FETCH_SESSIONS_REQUEST';
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_FAILURE = 'FETCH_SESSIONS_FAILURE';

export const FETCH_SESSION_BY_ID_REQUEST = 'FETCH_SESSION_BY_ID_REQUEST';
export const FETCH_SESSION_BY_ID_SUCCESS = 'FETCH_SESSION_BY_ID_SUCCESS';
export const FETCH_SESSION_BY_ID_FAILURE = 'FETCH_SESSION_BY_ID_FAILURE';

export const JOIN_SESSION_REQUEST = 'JOIN_SESSION_REQUEST';
export const JOIN_SESSION_SUCCESS = 'JOIN_SESSION_SUCCESS';
export const JOIN_SESSION_FAILURE = 'JOIN_SESSION_FAILURE';

export const LEAVE_SESSION_REQUEST = 'LEAVE_SESSION_REQUEST';
export const LEAVE_SESSION_SUCCESS = 'LEAVE_SESSION_SUCCESS';
export const LEAVE_SESSION_FAILURE = 'LEAVE_SESSION_FAILURE';

export const PLACE_BID_REQUEST = 'PLACE_BID_REQUEST';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_FAILURE = 'PLACE_BID_FAILURE';

export const UPDATE_PARTICIPANTS = 'UPDATE_PARTICIPANTS';

export const UPDATE_REMAINING_TIME = 'UPDATE_REMAINING_TIME'

export const AUCTION_ENDED = 'AUCTION_ENDED'