export const CREATE_AUCTION_REQUEST = 'CREATE_AUCTION_REQUEST';
export const CREATE_AUCTION_SUCCESS = 'CREATE_AUCTION_SUCCESS';
export const CREATE_AUCTION_FAILURE = 'CREATE_AUCTION_FAILURE';

export const DELETE_AUCTION_REQUEST = 'DELETE_AUCTION_REQUEST';
export const DELETE_AUCTION_SUCCESS = 'DELETE_AUCTION_SUCCESS';
export const DELETE_AUCTION_FAILURE = 'DELETE_AUCTION_FAILURE';

export const START_AUCTION_TIMER_REQUEST = 'START_AUCTION_TIMER_REQUEST';
export const START_AUCTION_TIMER_SUCCESS = 'START_AUCTION_TIMER_SUCCESS';
export const START_AUCTION_TIMER_FAILURE = 'START_AUCTION_TIMER_FAILURE';

export const PARTICIPANT_JOINED = 'PARTICIPANT_JOINED';

export const UPDATE_REMAINING_TIME = 'UPDATE_REMAINING_TIME'
export const AUCTION_ENDED = 'AUCTION_ENDED'

export const UPDATE_PARTICIPANTS = 'UPDATE_PARTICIPANTS'
